-- ============================================================================
-- CUSTOMERS / ORDERS
-- ============================================================================

CREATE TABLE "Customers" (
    "Id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "StoreId" UUID NOT NULL,
    "UserId" UUID NULL,
    "FirstName" VARCHAR(100) NOT NULL,
    "LastName" VARCHAR(100) NOT NULL,
    "Email" VARCHAR(255) NOT NULL,
    "Phone" VARCHAR(30) NULL,
    "DateOfBirth" DATE NULL,
    "Gender" VARCHAR(30) NULL,
    "IsGuest" BOOLEAN NOT NULL DEFAULT true,
    "AcceptsMarketing" BOOLEAN NOT NULL DEFAULT false,
    "IsActive" BOOLEAN NOT NULL DEFAULT true,
    "InternalNotes" TEXT NULL,
    "TotalOrdersCount" INTEGER NOT NULL DEFAULT 0,
    "TotalSpent" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "LastOrderDate" TIMESTAMPTZ NULL,
    "CreatedDate" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "CreatedBy" UUID NULL, "ModifiedDate" TIMESTAMPTZ NULL, "ModifiedBy" UUID NULL,
    "DeletedDate" TIMESTAMPTZ NULL, "DeletedBy" UUID NULL, "IsDeleted" BOOLEAN NOT NULL DEFAULT false,
    "Version" INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT "FK_Customers_Stores" FOREIGN KEY ("StoreId") REFERENCES "Stores"("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Customers_Users" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE SET NULL
);
CREATE INDEX "IX_Customers_StoreId_Email" ON "Customers" ("StoreId", "Email");

CREATE TABLE "Addresses" (
    "Id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "CustomerId" UUID NOT NULL,
    "Type" VARCHAR(20) NOT NULL DEFAULT 'Both',
    "FullName" VARCHAR(200) NOT NULL,
    "PhoneNumber" VARCHAR(30) NOT NULL,
    "AddressLine1" VARCHAR(255) NOT NULL,
    "AddressLine2" VARCHAR(255) NULL,
    "City" VARCHAR(100) NOT NULL,
    "State" VARCHAR(100) NOT NULL,
    "PostalCode" VARCHAR(20) NOT NULL,
    "CountryId" UUID NOT NULL,
    "IsDefaultShipping" BOOLEAN NOT NULL DEFAULT false,
    "IsDefaultBilling" BOOLEAN NOT NULL DEFAULT false,
    "CreatedDate" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "CreatedBy" UUID NULL, "ModifiedDate" TIMESTAMPTZ NULL, "ModifiedBy" UUID NULL,
    "DeletedDate" TIMESTAMPTZ NULL, "DeletedBy" UUID NULL, "IsDeleted" BOOLEAN NOT NULL DEFAULT false,
    "Version" INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT "FK_Addresses_Customers" FOREIGN KEY ("CustomerId") REFERENCES "Customers"("Id") ON DELETE CASCADE
);

CREATE TABLE "CartItems" (
    "Id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "CustomerId" UUID NOT NULL,
    "ProductId" UUID NOT NULL,
    "ProductVariantId" UUID NOT NULL,
    "Quantity" INTEGER NOT NULL,
    "AddedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "CreatedDate" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "CreatedBy" UUID NULL, "ModifiedDate" TIMESTAMPTZ NULL, "ModifiedBy" UUID NULL,
    "DeletedDate" TIMESTAMPTZ NULL, "DeletedBy" UUID NULL, "IsDeleted" BOOLEAN NOT NULL DEFAULT false,
    "Version" INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT "FK_CartItems_Customers" FOREIGN KEY ("CustomerId") REFERENCES "Customers"("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CartItems_Products" FOREIGN KEY ("ProductId") REFERENCES "Products"("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CartItems_Variants" FOREIGN KEY ("ProductVariantId") REFERENCES "ProductVariants"("Id") ON DELETE CASCADE,
    CONSTRAINT "UQ_CartItems_Customer_Variant" UNIQUE ("CustomerId", "ProductVariantId")
);

CREATE TABLE "Orders" (
    "Id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "StoreId" UUID NOT NULL,
    "OrderNumber" VARCHAR(50) NOT NULL,
    "CustomerId" UUID NOT NULL,
    "Status" VARCHAR(30) NOT NULL DEFAULT 'Pending',
    "PaymentStatus" VARCHAR(30) NOT NULL DEFAULT 'Pending',
    "CurrencyCode" VARCHAR(10) NOT NULL DEFAULT 'USD',
    "SubTotal" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "DiscountAmount" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "ShippingAmount" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "TaxAmount" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "TotalAmount" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "CouponId" UUID NULL,
    "CouponCode" VARCHAR(50) NULL,
    "ShippingMethodId" UUID NULL,
    "ShippingMethodName" VARCHAR(150) NULL,
    "ShippingFullName" VARCHAR(200) NULL,
    "ShippingPhoneNumber" VARCHAR(30) NULL,
    "ShippingAddressLine1" VARCHAR(255) NULL,
    "ShippingAddressLine2" VARCHAR(255) NULL,
    "ShippingCity" VARCHAR(100) NULL,
    "ShippingState" VARCHAR(100) NULL,
    "ShippingPostalCode" VARCHAR(20) NULL,
    "ShippingCountry" VARCHAR(100) NULL,
    "BillingFullName" VARCHAR(200) NULL,
    "BillingPhoneNumber" VARCHAR(30) NULL,
    "BillingAddressLine1" VARCHAR(255) NULL,
    "BillingAddressLine2" VARCHAR(255) NULL,
    "BillingCity" VARCHAR(100) NULL,
    "BillingState" VARCHAR(100) NULL,
    "BillingPostalCode" VARCHAR(20) NULL,
    "BillingCountry" VARCHAR(100) NULL,
    "CustomerNote" VARCHAR(1000) NULL,
    "InternalNote" VARCHAR(1000) NULL,
    "PaymentMethod" VARCHAR(50) NULL,
    "PlacedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "ConfirmedAt" TIMESTAMPTZ NULL,
    "ShippedAt" TIMESTAMPTZ NULL,
    "DeliveredAt" TIMESTAMPTZ NULL,
    "CancelledAt" TIMESTAMPTZ NULL,
    "CancelReason" VARCHAR(500) NULL,
    "UpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "CreatedDate" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "CreatedBy" UUID NULL, "ModifiedDate" TIMESTAMPTZ NULL, "ModifiedBy" UUID NULL,
    "DeletedDate" TIMESTAMPTZ NULL, "DeletedBy" UUID NULL, "IsDeleted" BOOLEAN NOT NULL DEFAULT false,
    "Version" INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT "FK_Orders_Stores" FOREIGN KEY ("StoreId") REFERENCES "Stores"("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Orders_Customers" FOREIGN KEY ("CustomerId") REFERENCES "Customers"("Id") ON DELETE RESTRICT
);
CREATE UNIQUE INDEX "UQ_Orders_StoreId_OrderNumber" ON "Orders" ("StoreId", "OrderNumber");
CREATE INDEX "IX_Orders_CustomerId" ON "Orders" ("CustomerId");
CREATE INDEX "IX_Orders_Status" ON "Orders" ("Status");

CREATE TABLE "OrderItems" (
    "Id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "OrderId" UUID NOT NULL,
    "ProductId" UUID NULL,
    "ProductVariantId" UUID NULL,
    "WarehouseId" UUID NULL,
    "ProductNameSnapshot" VARCHAR(300) NOT NULL,
    "VariantDisplayNameSnapshot" VARCHAR(300) NULL,
    "SkuSnapshot" VARCHAR(100) NOT NULL,
    "ImageUrlSnapshot" TEXT NULL,
    "UnitPrice" DECIMAL(12,2) NOT NULL,
    "Quantity" INTEGER NOT NULL,
    "DiscountAmount" DECIMAL(12,2) NOT NULL DEFAULT 0,
    "TaxAmount" DECIMAL(12,2) NOT NULL DEFAULT 0,
    "CreatedDate" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "CreatedBy" UUID NULL, "ModifiedDate" TIMESTAMPTZ NULL, "ModifiedBy" UUID NULL,
    "DeletedDate" TIMESTAMPTZ NULL, "DeletedBy" UUID NULL, "IsDeleted" BOOLEAN NOT NULL DEFAULT false,
    "Version" INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT "FK_OrderItems_Orders" FOREIGN KEY ("OrderId") REFERENCES "Orders"("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_OrderItems_Products" FOREIGN KEY ("ProductId") REFERENCES "Products"("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_OrderItems_Variants" FOREIGN KEY ("ProductVariantId") REFERENCES "ProductVariants"("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_OrderItems_Warehouses" FOREIGN KEY ("WarehouseId") REFERENCES "Warehouses"("Id") ON DELETE SET NULL
);
