using CommerceCore.Shared.Entities;

namespace CommerceCore.Domain.Entities.Billing;

/// <summary>
/// A GST-compliant B2C tax invoice generated automatically at checkout for one
/// Order. Every field that matters legally — seller GSTIN, invoice number, buyer
/// address, taxable value, CGST/SGST/IGST split — is snapshotted here rather than
/// computed on read, so a later change to the seller's GST settings never alters an
/// already-issued invoice (exactly the same snapshot principle Order/OrderItem
/// already follow for the same legal reason).
/// </summary>
public class Invoice : BaseEntity
{
    public Guid StoreId { get; set; }

    public Guid OrderId { get; set; }
    public Domain.Entities.Orders.Order? Order { get; set; }

    /// <summary>Sequential per store per Indian financial year, e.g. "INV/2526/000001"
    /// for financial year 2025-26. Generated by InvoiceSequence — never reused, never
    /// skipped, per GST invoice numbering rules.</summary>
    public string InvoiceNumber { get; set; } = string.Empty;
    public string FinancialYear { get; set; } = string.Empty; // "2025-26"
    public DateTime InvoiceDate { get; set; } = DateTime.UtcNow;

    // Seller details, snapshotted from StoreSettings at generation time.
    public string SellerLegalName { get; set; } = string.Empty;
    public string? SellerGstNumber { get; set; }
    public string? SellerPanNumber { get; set; }
    public string? SellerAddressLine1 { get; set; }
    public string? SellerAddressLine2 { get; set; }
    public string? SellerCity { get; set; }
    public string? SellerState { get; set; }
    public string? SellerPostalCode { get; set; }

    // Buyer (billing) details, snapshotted from the Order — B2C, so no buyer GSTIN.
    public string BuyerName { get; set; } = string.Empty;
    public string? BuyerAddressLine1 { get; set; }
    public string? BuyerAddressLine2 { get; set; }
    public string? BuyerCity { get; set; }
    public string? BuyerState { get; set; }
    public string? BuyerPostalCode { get; set; }
    public string? BuyerPhoneNumber { get; set; }

    public bool IsInterStateSupply { get; set; }
    public string PlaceOfSupplyState { get; set; } = string.Empty;

    public decimal TaxableValue { get; set; }     // subtotal after discount, before tax
    public decimal TotalCgstAmount { get; set; }
    public decimal TotalSgstAmount { get; set; }
    public decimal TotalIgstAmount { get; set; }
    public decimal TotalDiscountAmount { get; set; }
    public decimal TotalAmount { get; set; }       // grand total, matches Order.TotalAmount
}

/// <summary>
/// Tracks the last-used invoice number per Store per Indian financial year (April
/// 1 – March 31), so InvoiceNumber generation is a simple atomic increment rather
/// than a MAX(...) query racing against concurrent checkouts. One row per
/// (StoreId, FinancialYear) — created on first use of a new financial year.
/// </summary>
public class InvoiceSequence : BaseEntity
{
    public Guid StoreId { get; set; }
    public string FinancialYear { get; set; } = string.Empty; // "2025-26"
    public int LastNumber { get; set; }
}
